### PR TITLE
Made README.md more attractive

### PR DESCRIPTION
**Pull request by namantw**
Also added a picture made with canva

Fixes https://github.com/rahulkumaran/Utlyz-CLI/issues/13

### CODE REVIEW

**Comment by namantw** [comment]
@rahulkumaran please review :)

**Comment by rahulkumaran** [comment]
Can you add a screenshot for how each and every functionality works? just to make it look a little better

**Comment by namantw** [comment]
wouldn't that be a bit too much because there are a *lot* of functionalities, the README would look too clustered and unreadable

**Comment by rahulkumaran** [comment]
True that actually! But is it possible for you to add something more? like some image or some graphics? colors if possible? because it's too plain!

**Comment by namantw** [comment]
Okay I'm on it :D

**Comment by rahulkumaran** [comment]
Are you done with this @namantw ?

**Comment by namantw** [comment]
@rahulkumaran 
image
More images? like command screen shots?

**Comment by rahulkumaran** [comment]
Yeah! Not many but maybe like one 2 showing how it works!

**Comment by rahulkumaran** [comment]
Thanks for your contribution :smile: @namantw

**Pull request merged**
