### PR TITLE
Added new code for wishing Happy Birthday, from command line

### PR DESCRIPTION
**Pull request by namantw**
I have just added the main code, but I have yet to test it properly. I used `fbchat` and `getpass` as additional modules.
Make sure to `pip install fbchat` manually as it not added in the dependencies and haven't made changes in `setup.py` for now (once we are done prototyping I'll do everything)
@rahulkumaran please see the code :man_technologist:

### CODE REVIEW

**Comment by rahulkumaran** [comment]
Great! Ill have a look at this asap and I'll get back to you

**Comment by rahulkumaran** [comment]
And also, can you specify any problems you're facing ? So that I can take deeper look at those points too?

**Comment by namantw** [comment]
@rahulkumaran installation works smoothly, but to test it I need a Facebook account who has a birthday, and creating a Fake ID and testing it is taking time, any suggestions how to test it?

**Comment by rahulkumaran** [comment]
I'll test it and have a look! I have a couple of test IDs that I created! Ill test it for you and tell you if it works! I'll let you know by tonight

Just a small advice! Have a testing account on Gmail and Facebook always! It'll help you to perform tasks easily! Like you know you can test your code easily!

**Comment by namantw** [comment]
Okay, by the way are you taking part as a contestant too because I saw you solving issues in PyDic

**Comment by rahulkumaran** [comment]
@namatw haha, yes! I'm taking part as a contestant too ! 
There's always a scope to learn more when you're participating as well apart from just mentoring

**Comment by rahulkumaran** [comment]
Sorry for the delay! Had a couple of assignments to submit in college! Anyway, I've had a look at this! I'm in class right now! Once I'm back to my room, I'll tell you how it worked! :)

**Comment by Anupam-dagar** [comment]
@rahulkumaran can you merge this PR?

**Comment by rahulkumaran** [comment]
@Anupam-dagar, nope! Results not as expected! So won't be able to merge this!

**Pull request closed without merging**
